# Generated by Django 5.2.10 on 2026-01-28 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='girlprofile',
            name='story',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='GirlPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('girl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.girlprofile')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
