AdvancedOptions: false
RuntimeType: Container
DockerFilePath: Dockerfile
ServiceType: private
ArtifactSourceType: Dockerfile
ServiceBuildRegion: cn-hangzhou
RepoName: UUsatova/girls-backend
RegionId: ap-southeast-1
Owner: UUsatova
Branch: main
Platform: github
